### PR TITLE
Add tests, explicit pins/builds for 2.1.(<4)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for getting the ball rolling on this, but I've still had a lot of trouble getting it to actually do even the simplest task when installed.

This adds the combinations that I've been able to to get working (on linux) that can actually do the simplest example from the README as well as run the bundled tests. Anything newer seems to break either in the bundled tests or the README example. ~~They also don't seem to be cross-compatible, e.g. one built with `spacy 2.1.1` will coredump when tested next to `spacy 2.1.2`.~~ Building with 2.1.1 does seem to work when installed with 2.1.2 and 2.1.3.

I'd also love to figure out how to get the pre-trained model packaged: at present, that probably just means another package with an activation script to set the environment variable for the cache location... but that's for another day! Something that works at all is a great first step!

### CODE REVIEW

**Comment by bollwyvl** [comment]
>  They also don't seem to be cross-compatible, e.g. one built with spacy 2.1.1 will coredump when tested next to spacy 2.1.2.

I think I sorted this by removing `conda_build_config.yaml` and changing the pins around. This cut the number of builds down by 2/3 so is probably worth doing.

**Comment by oblute** [comment]
@bollwyvl thanks so much for your PR. there are a lot of incompatibility issues with new versions of spaCy, and it's _many_ strictly pinned dependencies, that make this package a bit finnicky, as I'm sure you know; depending on whichever spaCy version users had in their environment during installation could lead to different results. (discussions shown in these issues: https://github.com/huggingface/neuralcoref/issues/167 https://github.com/huggingface/neuralcoref/issues/103)

few questions for you regarding your changes. i don't believe it's best practice to have different pins in host and run req - is there a reason you did this? i would suggest we have the looser pins in both run and host, to keep the recipe clearer. it's also common in the conda-forge to have the loosest pins possible, so that if future spaCy development allowed newer versions to be compatible with neuralcoref, it wouldn't require changing here. second, is wheel actually required in host? it would be unusual and doesn't seem necessary for me.

in terms of loading in the spaCy model for testing - that is a smart addition. it's done in the allennlp feedstock https://github.com/conda-forge/allennlp-feedstock/blob/master/recipe/meta.yaml a bit differently that also allows for a test command to ensure it was properly loaded. this may be a better route?

**Comment by oblute** [comment]
@bollwyvl we may also need to include a line regarding binary relocation, as seen in the read me https://github.com/huggingface/neuralcoref#spacystringsstringstore-size-changed-error -- `binary_relocation: False` in the build part of the recipe

**Comment by bollwyvl** [comment]
> different pins in host and run req

This was to demonstrate that building with the oldest version would work with the last supported version. I've set them to be more "permissive", but the binary compatibility window is still very small.

> loosest pins possible,

This is as loose as actually works from 100-odd builds. Given there hasn't been a release of this package in a year, I wouldn't be too worried about the maintainability, instead let's get something that isn't broken-by-default out there (and probably mark the current packages broken). 

With the tests added, it will fail loudly when a future version lands, and then if it supports `2.1` and `2.x`, all the better, but it seems more likely it will only support whatever the next release of spacy will be: none of the existing `2.2` releases will work because the source distribution doesn't include the `pxd`, and matching them exactly is... fun.

> wheel

Yes, it doesn't build otherwise.

>  test command to ensure it was properly loaded

This is in the `run_test.py`, which `conda-build` will pick up, as can be seen in the test log:

```
running run_test.py

    Running simplest example adapted from:

    https://github.com/huggingface/neuralcoref/blob/4.0.0/README.md#loading-neuralcoref



  0%|          | 0/40155833 [00:00<?, ?B/s]
  9%|▉         | 3559424/40155833 [00:00<00:01, 35593849.63B/s]
 22%|██▏       | 8697856/40155833 [00:00<00:00, 39206707.84B/s]
 34%|███▍      | 13845504/40155833 [00:00<00:00, 42223363.30B/s]
 47%|████▋     | 18964480/40155833 [00:00<00:00, 44564685.21B/s]
 60%|██████    | 24133632/40155833 [00:00<00:00, 46487111.13B/s]
 71%|███████   | 28422144/40155833 [00:00<00:00, 45344419.06B/s]
 83%|████████▎ | 33384448/40155833 [00:00<00:00, 46546271.59B/s]
 96%|█████████▌| 38455296/40155833 [00:00<00:00, 47720042.48B/s]
100%|██████████| 40155833/40155833 [00:00<00:00, 48209665.93B/s]
True
[My sister: [My sister, She], a dog: [a dog, him]]
```

>  binary relocation

We're building from source, with all headers provided by other source builds in this case. The errors mentioned are mostly about the pypi wheels not being binary compatible. If someone tries to `conda` install `neuralcoref` on top of a `pip` installed `spacy`, they're asking for trouble anyways.

**Comment by oblute** [comment]
@bollwyvl thanks for the detailed response. i have this building currently without wheel, so i'm not sure why it's required for you? let's bump the build number back to 1 and then we should be good to merge.

**Comment by oblute** [comment]
thanks @bollwyvl!

**Comment by bollwyvl** [comment]
Hooray!

**Comment by bollwyvl** [comment]
Looks like the build number should be bumped: there were already _1
releases.

**Pull request merged**
